# Generated by Django 6.1.1 on 2026-09-19 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
